services:
  - type: web
    name: ngm-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn api.main:app -w ${GUNICORN_WORKERS:-1} -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000 --timeout 120 --max-requests 5000 --max-requests-jitter 200
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
    # Paquetes del sistema necesarios
    nativeEnvironments:
      - name: poppler-utils
